#include <stdlib.h>
#include <string.h>
#include <stdio.h> // Include for printf
#include "scripting/embedded_scripts.h"

/* Structure to hold an embedded script */
typedef struct {
    const char *name;
    const char *content;
} EmbeddedScript;

/* Array of embedded scripts */
static const EmbeddedScript embedded_scripts[] = {
    /* main.lua */
    {
        "main.lua",
        "-- Updated main.lua for Lua 5\n"
        "print(\"[lua] Starting main.lua\")\n"
        "\n"
        "-- Define return codes\n"
        "EScriptingReturnCode = {\n"
        "    eSRC_Quit = 0,\n"
        "    eSRC_Game_End = 1,\n"
        "    eSRC_Game_Pause = 2,\n"
        "    eSRC_Game_Unpause = 3,\n"
        "    eSRC_Game_Credits = 4,\n"
        "    eSRC_Game_Escape = 5,\n"
        "    eSRC_Timedemo = 7,\n"
        "    eSRC_Timedemo_Abort = 8,\n"
        "    eSRC_Credits = 9,\n"
        "    eSRC_Game_Launch = 10,\n"
        "    eSRC_GUI_Escape = 11,\n"
        "    eSRC_GUI_Prompt = 12,\n"
        "    eSRC_GUI_Prompt_Escape = 13,\n"
        "    eSRC_Pause_Escape = 14,\n"
        "    eSRC_32bitWarning_OK = 15,\n"
        "}\n"
        "\n"
        "-- Check for timedemo mode\n"
        "timedemo = nil\n"
        "-- timedemo = 1\n"
        "if(timedemo) then\n"
        "    print(\"[lua] Running in timedemo mode\")\n"
        "    c_setCallback(\"timedemo\")\n"
        "    c_mainLoop()\n"
        "    os.exit()\n"
        "end\n"
        "\n"
        "-- Initialize variables\n"
        "if callback == nil then\n"
        "    callback = \"gui\"\n"
        "end\n"
        "\n"
        "if Menu == nil then\n"
        "    Menu = MainGameMenu\n"
        "end\n"
        "\n"
        "game_initialized = 0\n"
        "\n"
        "-- Define callback handlers\n"
        "next_callback = {}\n"
        "next_callback[EScriptingReturnCode.eSRC_Game_Launch] = function()\n"
        "    game_initialized = 1\n"
        "    return \"pause\"\n"
        "end\n"
        "next_callback[EScriptingReturnCode.eSRC_Game_End] = function() return \"pause\" end\n"
        "next_callback[EScriptingReturnCode.eSRC_Game_Pause] = function() return \"pause\" end\n"
        "next_callback[EScriptingReturnCode.eSRC_Game_Unpause] = function() return \"game\" end\n"
        "next_callback[EScriptingReturnCode.eSRC_Credits] = function() return \"credits\" end\n"
        "next_callback[EScriptingReturnCode.eSRC_Game_Escape] = function() return \"gui\" end\n"
        "next_callback[EScriptingReturnCode.eSRC_GUI_Escape] = function()\n"
        "    if(game_initialized == 1) then\n"
        "        return \"pause\"\n"
        "    else\n"
        "        return \"gui\"\n"
        "    end\n"
        "end\n"
        "next_callback[EScriptingReturnCode.eSRC_GUI_Prompt_Escape] = function() return \"gui\" end\n"
        "next_callback[EScriptingReturnCode.eSRC_Pause_Escape] = function() return \"gui\" end\n"
        "next_callback[EScriptingReturnCode.eSRC_GUI_Prompt] = function() return \"configure\" end\n"
        "next_callback[EScriptingReturnCode.eSRC_32bitWarning_OK] = function() return \"gui\" end\n"
        "\n"
        "-- Main loop\n"
        "print(\"[lua] Starting main loop\")\n"
        "while true do\n"
        "    -- Set callback\n"
        "    c_setCallback(callback)\n"
        "    print(\"[lua] Setting callback: \" .. callback)\n"
        "    \n"
        "    -- Run main loop\n"
        "    local status = c_mainLoop()\n"
        "    print(\"[lua] System returned: \" .. tostring(status))\n"
        "    \n"
        "    -- Handle return code\n"
        "    if next_callback[status] then\n"
        "        callback = next_callback[status]()\n"
        "    else\n"
        "        if status == EScriptingReturnCode.eSRC_Quit then\n"
        "            print(\"[lua] Clean exit\")\n"
        "            break\n"
        "        else\n"
        "            print(\"[lua] Unhandled callback (\" .. tostring(status) .. \")\")\n"
        "            break\n"
        "        end\n"
        "    end\n"
        "end\n"
        "\n"
        "print(\"[lua] main.lua completed\")\n"
    },
    
    /* menu_functions.lua */
    {
        "menu_functions.lua",
        "-- Minimal menu_functions.lua\n"
        "print(\"[menu_functions] Loading minimal menu_functions.lua\")\n"
        "\n"
        "-- Define Menu table if it doesn't exist\n"
        "if not Menu then\n"
        "    Menu = {\n"
        "        current = \"RootMenu\",\n"
        "        action = function(action_type, action_value)\n"
        "            print(\"[menu_functions] Menu action: \" .. tostring(action_type) .. \", \" .. tostring(action_value))\n"
        "            return 1\n"
        "        end\n"
        "    }\n"
        "    print(\"[menu_functions] Created Menu table\")\n"
        "end\n"
        "\n"
        "-- Define basic menu functions\n"
        "function createMenu(name)\n"
        "    print(\"[menu_functions] Creating menu: \" .. name)\n"
        "    return {\n"
        "        name = name,\n"
        "        items = {},\n"
        "        selected = 1\n"
        "    }\n"
        "end\n"
        "\n"
        "function addMenuItem(menu, item)\n"
        "    print(\"[menu_functions] Adding menu item to \" .. menu.name)\n"
        "    table.insert(menu.items, item)\n"
        "end\n"
        "\n"
        "-- Create root menu\n"
        "RootMenu = createMenu(\"RootMenu\")\n"
        "addMenuItem(RootMenu, { name = \"Start Game\", action = \"startGame\" })\n"
        "addMenuItem(RootMenu, { name = \"Settings\", action = \"showSettings\" })\n"
        "addMenuItem(RootMenu, { name = \"Quit\", action = \"quit\" })\n"
        "\n"
        "-- Set current menu\n"
        "Menu.current = \"RootMenu\"\n"
        "\n"
        "print(\"[menu_functions] Minimal menu_functions.lua loaded\")\n"
        "return true\n"
    },

    /* game_init.lua */
    {
        "game_init.lua",
        "-- Game initialization script\n"
        "print(\"[game_init] Initializing game\")\n"
        "\n"
        "-- Set up game parameters\n"
        "if settings then\n"
        "    -- Apply game settings\n"
        "    print(\"[game_init] Applying game settings\")\n"
        "    \n"
        "    -- Example: Set game speed\n"
        "    if settings.speed then\n"
        "        print(\"[game_init] Setting game speed to \" .. settings.speed)\n"
        "    end\n"
        "    \n"
        "    -- Example: Set game difficulty\n"
        "    if settings.difficulty then\n"
        "        print(\"[game_init] Setting game difficulty to \" .. settings.difficulty)\n"
        "    end\n"
        "end\n"
        "\n"
        "-- Initialize game variables\n"
        "print(\"[game_init] Initializing game variables\")\n"
        "\n"
        "-- Example: Set up player data\n"
        "if not player_data then\n"
        "    player_data = {}\n"
        "    print(\"[game_init] Created player_data table\")\n"
        "end\n"
        "\n"
        "-- Example: Set up level data\n"
        "if not level_data then\n"
        "    level_data = {}\n"
        "    print(\"[game_init] Created level_data table\")\n"
        "end\n"
        "\n"
        "print(\"[game_init] Game initialization complete\")\n"
        "return true\n"
    },
    
    /* console.lua */
    {
        "console.lua",
        "-- Console script\n"
        "print(\"[console] Loading console script\")\n"
        "\n"
        "-- Define console functions\n"
        "console = {}\n"
        "\n"
        "function console.print(message)\n"
        "    print(\"[console] \" .. tostring(message))\n"
        "end\n"
        "\n"
        "function console.execute(command)\n"
        "    print(\"[console] Executing: \" .. command)\n"
        "    local func, err = loadstring(command)\n"
        "    if func then\n"
        "        local status, result = pcall(func)\n"
        "        if status then\n"
        "            return result\n"
        "        else\n"
        "            print(\"[console] Error executing command: \" .. tostring(result))\n"
        "            return nil\n"
        "        end\n"
        "    else\n"
        "        print(\"[console] Error parsing command: \" .. tostring(err))\n"
        "        return nil\n"
        "    end\n"
        "end\n"
        "\n"
        "print(\"[console] Console script loaded\")\n"
        "return true\n"
    },
    
    /* layout.lua */
    {
        "layout.lua",
        "-- Layout script\n"
        "print(\"[layout] Loading layout script\")\n"
        "\n"
        "-- Define layout functions\n"
        "layout = {}\n"
        "\n"
        "function layout.center(width, height)\n"
        "    print(\"[layout] Centering element with dimensions: \" .. width .. \"x\" .. height)\n"
        "    return 0, 0\n"
        "end\n"
        "\n"
        "print(\"[layout] Layout script loaded\")\n"
        "return true\n"
    },
    
    /* play_music.lua */
    {
        "play_music.lua",
        "-- Play music script\n"
        "print(\"[play_music] Loading play music script\")\n"
        "\n"
        "-- Define music functions\n"
        "function play_music()\n"
        "    print(\"[play_music] Playing music\")\n"
        "    if c_reloadTrack then\n"
        "        c_reloadTrack()\n"
        "        return true\n"
        "    else\n"
        "        print(\"[play_music] c_reloadTrack function not available\")\n"
        "        return false\n"
        "    end\n"
        "end\n"
        "\n"
        "print(\"[play_music] Play music script loaded\")\n"
        "return true\n"
    },
    
    /* direct_music_player.lua */
    {
        "direct_music_player.lua",
        "-- Direct music player script\n"
        "print(\"[direct_music] Loading direct music player script\")\n"
        "\n"
        "-- Function to play music\n"
        "function play_music()\n"
        "    print(\"[direct_music] Attempting to play music\")\n"
        "    \n"
        "    -- Make sure music is enabled in settings\n"
        "    if settings and settings.playMusic == nil then\n"
        "        settings.playMusic = 1\n"
        "        print(\"[direct_music] Enabled music in settings\")\n"
        "    end\n"
        "    \n"
        "    -- Set music volume if not set\n"
        "    if settings and settings.musicVolume == nil then\n"
        "        settings.musicVolume = 0.8\n"
        "        print(\"[direct_music] Set music volume to 0.8\")\n"
        "    end\n"
        "    \n"
        "    -- Update audio volume if function exists\n"
        "    if c_update_audio_volume and type(c_update_audio_volume) == \"function\" then\n"
        "        print(\"[direct_music] Updating audio volume\")\n"
        "        c_update_audio_volume()\n"
        "    end\n"
        "    \n"
        "    -- Try to find a music file\n"
        "    local music_file = \"music/song_revenge_of_cats.it\"\n"
        "    print(\"[direct_music] Looking for music file: \" .. music_file)\n"
        "    \n"
        "    -- Set as current track in settings\n"
        "    if settings then\n"
        "        settings.current_track = \"song_revenge_of_cats.it\"\n"
        "        print(\"[direct_music] Set current_track to: \" .. settings.current_track)\n"
        "    end\n"
        "    \n"
        "    -- Try to play the music\n"
        "    if c_reloadTrack and type(c_reloadTrack) == \"function\" then\n"
        "        print(\"[direct_music] Calling c_reloadTrack()\")\n"
        "        c_reloadTrack()\n"
        "        return true\n"
        "    else\n"
        "        print(\"[direct_music] c_reloadTrack not available\")\n"
        "        return false\n"
        "    end\n"
        "end\n"
        "\n"
        "-- Call the function\n"
        "print(\"[direct_music] Executing play_music()\")\n"
        "local success = play_music()\n"
        "print(\"[direct_music] play_music() returned: \" .. tostring(success))\n"
        "\n"
        "return success\n"
    },
    
    /* save.lua */
    {
        "save.lua",
        "-- Save script\n"
        "print(\"[save] Loading save script\")\n"
        "\n"
        "-- Load music functions if they're not already loaded\n"
        "if not nextTrack then\n"
        "    print(\"[save] Loading music functions\")\n"
        "    dofile(\"scripts/music_functions.lua\")\n"
        "end\n"
        "\n"
        "-- Function to save settings\n"
        "function saveSettings()\n"
        "    print(\"[save] Saving settings\")\n"
        "    \n"
        "    -- Make sure music is enabled\n"
        "    if settings.playMusic == nil then\n"
        "        settings.playMusic = 1\n"
        "        print(\"[save] Enabled music (was nil)\")\n"
        "    end\n"
        "    \n"
        "    -- Set music volume if not set\n"
        "    if settings.musicVolume == nil or settings.musicVolume == 0 then\n"
        "        settings.musicVolume = 0.8\n"
        "        print(\"[save] Set music volume to 0.8\")\n"
        "    end\n"
        "    \n"
        "    -- Update audio volume\n"
        "    if c_update_audio_volume then\n"
        "        c_update_audio_volume()\n"
        "    end\n"
        "    \n"
        "    -- Try to play music if it's not already playing\n"
        "    if settings.playMusic == 1 and settings.current_track == nil then\n"
        "        print(\"[save] No current track set, trying to play music\")\n"
        "        if nextTrack then\n"
        "            nextTrack()\n"
        "        end\n"
        "    end\n"
        "    \n"
        "    return 1\n"
        "end\n"
        "\n"
        "-- Function to load settings\n"
        "function loadSettings()\n"
        "    print(\"[save] Loading settings\")\n"
        "    \n"
        "    -- Make sure music is enabled\n"
        "    if settings.playMusic == nil then\n"
        "        settings.playMusic = 1\n"
        "        print(\"[save] Enabled music (was nil)\")\n"
        "    end\n"
        "    \n"
        "    -- Set music volume if not set\n"
        "    if settings.musicVolume == nil or settings.musicVolume == 0 then\n"
        "        settings.musicVolume = 0.8\n"
        "        print(\"[save] Set music volume to 0.8\")\n"
        "    end\n"
        "    \n"
        "    -- Update audio volume\n"
        "    if c_update_audio_volume then\n"
        "        c_update_audio_volume()\n"
        "    end\n"
        "    \n"
        "    -- Try to play music if it's not already playing\n"
        "    if settings.playMusic == 1 and settings.current_track == nil then\n"
        "        print(\"[save] No current track set, trying to play music\")\n"
        "        if nextTrack then\n"
        "            nextTrack()\n"
        "        end\n"
        "    elseif settings.playMusic == 1 and settings.current_track then\n"
        "        print(\"[save] Current track is set to: \" .. settings.current_track)\n"
        "        if c_reloadTrack then\n"
        "            print(\"[save] Calling c_reloadTrack()\")\n"
        "            c_reloadTrack()\n"
        "        end\n"
        "    end\n"
        "    \n"
        "    return 1\n"
        "end\n"
        "\n"
        "-- Call loadSettings to initialize\n"
        "loadSettings()\n"
        "\n"
        "print(\"[save] Save script loaded\")\n"
        "\n"
        "return 1\n"
    },
    
    /* android_touch.lua */
    {
        "android_touch.lua",
        "-- Android touch script\n"
        "print(\"[android_touch] Loading Android touch script\")\n"
        "\n"
        "-- Check if we're on Android\n"
        "local is_android = false\n"
        "if c_is_android and c_is_android() then\n"
        "    is_android = true\n"
        "    print(\"[android_touch] Running on Android\")\n"
        "else\n"
        "    print(\"[android_touch] Not running on Android\")\n"
        "end\n"
        "\n"
        "-- Set up touch controls if on Android\n"
        "if is_android then\n"
        "    print(\"[android_touch] Setting up touch controls\")\n"
        "    \n"
        "    -- Set touch mode\n"
        "    if c_set_touch_mode then\n"
        "        c_set_touch_mode(1)  -- 1 = swipe mode\n"
        "        print(\"[android_touch] Set touch mode to swipe\")\n"
        "    end\n"
        "    \n"
        "    -- Set swipe threshold\n"
        "    if c_set_touch_swipe_threshold then\n"
        "        c_set_touch_swipe_threshold(50)  -- 50 pixels\n"
        "        print(\"[android_touch] Set swipe threshold to 50 pixels\")\n"
        "    end\n"
        "end\n"
        "\n"
        "print(\"[android_touch] Android touch script loaded\")\n"
        "return true\n"
    },
    
    /* force_music.lua */
    {
        "force_music.lua",
        "-- Force music script\n"
        "print(\"[force_music] Loading force music script\")\n"
        "\n"
        "-- Function to force music to play\n"
        "function force_music_play()\n"
        "    print(\"[force_music] Forcing music to play\")\n"
        "    \n"
        "    -- Make sure music is enabled\n"
        "    if settings.playMusic == nil then\n"
        "        settings.playMusic = 1\n"
        "        print(\"[force_music] Enabled music (was nil)\")\n"
        "    elseif settings.playMusic == 0 then\n"
        "        settings.playMusic = 1\n"
        "        print(\"[force_music] Enabled music (was 0)\")\n"
        "    end\n"
        "    \n"
        "    -- Set music volume if not set\n"
        "    if settings.musicVolume == nil or settings.musicVolume == 0 then\n"
        "        settings.musicVolume = 0.8\n"
        "        print(\"[force_music] Set music volume to 0.8\")\n"
        "    end\n"
        "    \n"
        "    -- Update audio volume\n"
        "    if c_update_audio_volume then\n"
        "        c_update_audio_volume()\n"
        "    end\n"
        "    \n"
        "    -- Try to find a music file\n"
        "    local music_file = \"music/song_revenge_of_cats.it\"\n"
        "    \n"
        "    -- Set as current track\n"
        "    settings.current_track = \"song_revenge_of_cats.it\"\n"
        "    print(\"[force_music] Set current_track to: \" .. settings.current_track)\n"
        "    \n"
        "    -- Try to play the music\n"
        "    if c_reloadTrack then\n"
        "        print(\"[force_music] Calling c_reloadTrack()\")\n"
        "        c_reloadTrack()\n"
        "        return true\n"
        "    else\n"
        "        print(\"[force_music] c_reloadTrack not available\")\n"
        "        return false\n"
        "    end\n"
        "end\n"
        "\n"
        "-- Call the function\n"
        "local success = force_music_play()\n"
        "print(\"[force_music] Result: \" .. tostring(success))\n"
        "\n"
        "return success\n"
    },
    
    /* menu.lua */
    {
        "menu.lua",
        "-- Menu script\n"
        "print(\"[menu] Loading menu script\")\n"
        "\n"
        "-- Make sure menu_functions is loaded\n"
        "if not Menu then\n"
        "    print(\"[menu] Loading menu_functions\")\n"
        "    dofile(\"scripts/menu_functions.lua\")\n"
        "end\n"
        "\n"
        "-- Function to handle menu input\n"
        "function handleMenuInput(input)\n"
        "    print(\"[menu] Handling input: \" .. input)\n"
        "    \n"
        "    if input == \"up\" then\n"
        "        -- Move selection up\n"
        "        local menu = _G[Menu.current]\n"
        "        if menu and menu.selected > 1 then\n"
        "            menu.selected = menu.selected - 1\n"
        "            print(\"[menu] Selected item: \" .. menu.selected)\n"
        "        end\n"
        "    elseif input == \"down\" then\n"
        "        -- Move selection down\n"
        "        local menu = _G[Menu.current]\n"
        "        if menu and menu.selected < #menu.items then\n"
        "            menu.selected = menu.selected + 1\n"
        "            print(\"[menu] Selected item: \" .. menu.selected)\n"
        "        end\n"
        "    elseif input == \"select\" then\n"
        "        -- Select current item\n"
        "        local menu = _G[Menu.current]\n"
        "        if menu and menu.items[menu.selected] then\n"
        "            local item = menu.items[menu.selected]\n"
        "            print(\"[menu] Selected: \" .. item.name)\n"
        "            \n"
        "            if item.action == \"startGame\" then\n"
        "                print(\"[menu] Starting game\")\n"
        "                if c_startGame then\n"
        "                    c_startGame()\n"
        "                end\n"
        "            elseif item.action == \"quit\" then\n"
        "                print(\"[menu] Quitting game\")\n"
        "                if c_quitGame then\n"
        "                    c_quitGame()\n"
        "                end\n"
        "            end\n"
        "        end\n"
        "    end\n"
        "end\n"
        "\n"
        "print(\"[menu] Menu script loaded\")\n"
        "return true\n"
    },
    
    /* artpack.lua */
    {
        "artpack.lua",
        "-- Artpack script\n"
        "print(\"[artpack] Loading artpack script\")\n"
        "\n"
        "-- Initialize artpacks table\n"
        "if not artpacks then\n"
        "    artpacks = {}\n"
        "    print(\"[artpack] Created artpacks table\")\n"
        "end\n"
        "\n"
        "-- Function to set up artpack paths\n"
        "function setupArtpackPaths()\n"
        "    print(\"[artpack] Setting up artpack paths\")\n"
        "    \n"
        "    -- Make sure current_artpack is set\n"
        "    if not settings.current_artpack then\n"
        "        settings.current_artpack = \"default\"\n"
        "        print(\"[artpack] Set current_artpack to default\")\n"
        "    end\n"
        "    \n"
        "    -- Set up artpack paths\n"
        "    if c_setArtPath then\n"
        "        c_setArtPath()\n"
        "        print(\"[artpack] Set art path to: \" .. settings.current_artpack)\n"
        "    end\n"
        "end\n"
        "\n"
        "print(\"[artpack] Artpack script loaded\")\n"
        "return true\n"
    },
    
    /* game.lua */
    {
        "game.lua",
        "-- Game script\n"
        "print(\"[game] Loading game script\")\n"
        "\n"
        "-- Initialize game settings\n"
        "if not settings.speed then\n"
        "    settings.speed = 10.0\n"
        "    print(\"[game] Set default speed to 10.0\")\n"
        "end\n"
        "\n"
        "if not settings.players then\n"
        "    settings.players = 1\n"
        "    print(\"[game] Set default players to 1\")\n"
        "end\n"
        "\n"
        "if not settings.ai_opponents then\n"
        "    settings.ai_opponents = 3\n"
        "    print(\"[game] Set default AI opponents to 3\")\n"
        "end\n"
        "\n"
        "-- Function to start the game\n"
        "function startGame()\n"
        "    print(\"[game] Starting game\")\n"
        "    \n"
        "    if c_startGame then\n"
        "        c_startGame()\n"
        "        return true\n"
        "    else\n"
        "        print(\"[game] c_startGame function not available\")\n"
        "        return false\n"
        "    end\n"
        "end\n"
        "\n"
        "print(\"[game] Game script loaded\")\n"
        "return true\n"
    },
    
    /* music_functions.lua */
    {
        "music_functions.lua",
        "-- Music functions script\n"
        "print(\"[music_functions] Loading music functions script\")\n"
        "\n"
        "-- Initialize tracks table\n"
        "if not tracks then\n"
        "    tracks = {}\n"
        "    table.insert(tracks, \"music/song_revenge_of_cats.it\")\n"
        "    print(\"[music_functions] Added default track\")\n"
        "end\n"
        "\n"
        "-- Initialize current_track_index if it doesn't exist\n"
        "if not current_track_index then\n"
        "    current_track_index = 1\n"
        "    print(\"[music_functions] Set current_track_index to 1\")\n"
        "end\n"
        "\n"
        "-- Function to get the next track\n"
        "function nextTrack()\n"
        "    print(\"[music_functions] nextTrack() called\")\n"
        "    \n"
        "    if #tracks == 0 then\n"
        "        print(\"[music_functions] No tracks available\")\n"
        "        return false\n"
        "    end\n"
        "    \n"
        "    -- Move to next track\n"
        "    current_track_index = current_track_index + 1\n"
        "    if current_track_index > #tracks then\n"
        "        current_track_index = 1\n"
        "    end\n"
        "    \n"
        "    -- Get the track path\n"
        "    local track_path = tracks[current_track_index]\n"
        "    print(\"[music_functions] Next track: \" .. track_path)\n"
        "    \n"
        "    -- Extract filename from path\n"
        "    local filename = string.gsub(track_path, \"^.*/\", \"\")\n"
        "    print(\"[music_functions] Extracted filename: \" .. filename)\n"
        "    \n"
        "    -- Set as current track\n"
        "    if settings then\n"
        "        settings.current_track = filename\n"
        "        print(\"[music_functions] Set current_track to: \" .. filename)\n"
        "    end\n"
        "    \n"
        "    -- Try to play the music\n"
        "    if c_reloadTrack and type(c_reloadTrack) == \"function\" then\n"
        "        print(\"[music_functions] Calling c_reloadTrack()\")\n"
        "        c_reloadTrack()\n"
        "        return true\n"
        "    else\n"
        "        print(\"[music_functions] c_reloadTrack not available\")\n"
        "        return false\n"
        "    end\n"
        "end\n"
        "\n"
        "-- Function to get the previous track\n"
        "function previousTrack()\n"
        "    print(\"[music_functions] previousTrack() called\")\n"
        "    \n"
        "    if #tracks == 0 then\n"
        "        print(\"[music_functions] No tracks available\")\n"
        "        return false\n"
        "    end\n"
        "    \n"
        "    -- Move to previous track\n"
        "    current_track_index = current_track_index - 1\n"
        "    if current_track_index < 1 then\n"
        "        current_track_index = #tracks\n"
        "    end\n"
        "    \n"
        "    -- Get the track path\n"
        "    local track_path = tracks[current_track_index]\n"
        "    print(\"[music_functions] Previous track: \" .. track_path)\n"
        "    \n"
        "    -- Extract filename from path\n"
        "    local filename = string.gsub(track_path, \"^.*/\", \"\")\n"
        "    print(\"[music_functions] Extracted filename: \" .. filename)\n"
        "    \n"
        "    -- Set as current track\n"
        "    if settings then\n"
        "        settings.current_track = filename\n"
        "        print(\"[music_functions] Set current_track to: \" .. filename)\n"
        "    end\n"
        "    \n"
        "    -- Try to play the music\n"
        "    if c_reloadTrack and type(c_reloadTrack) == \"function\" then\n"
        "        print(\"[music_functions] Calling c_reloadTrack()\")\n"
        "        c_reloadTrack()\n"
        "        return true\n"
        "    else\n"
        "        print(\"[music_functions] c_reloadTrack not available\")\n"
        "        return false\n"
        "    end\n"
        "end\n"
        "\n"
        "-- Helper functions for volume control\n"
        "function MusicVolumeUp()\n"
        "    print(\"[music_functions] MusicVolumeUp() called\")\n"
        "    \n"
        "    if settings.musicVolume < 1.0 then\n"
        "        settings.musicVolume = settings.musicVolume + 0.1\n"
        "        if settings.musicVolume > 1.0 then\n"
        "            settings.musicVolume = 1.0\n"
        "        end\n"
        "        \n"
        "        if c_update_audio_volume then\n"
        "            c_update_audio_volume()\n"
        "        end\n"
        "    end\n"
        "end\n"
        "\n"
        "function MusicVolumeDown()\n"
        "    print(\"[music_functions] MusicVolumeDown() called\")\n"
        "    \n"
        "    if settings.musicVolume > 0.0 then\n"
        "        settings.musicVolume = settings.musicVolume - 0.1\n"
        "        if settings.musicVolume < 0.0 then\n"
        "            settings.musicVolume = 0.0\n"
        "        end\n"
        "        \n"
        "        if c_update_audio_volume then\n"
        "            c_update_audio_volume()\n"
        "        end\n"
        "    end\n"
        "end\n"
        "\n"
        "function FXVolumeUp()\n"
        "    print(\"[music_functions] FXVolumeUp() called\")\n"
        "    \n"
        "    if settings.fxVolume < 1.0 then\n"
        "        settings.fxVolume = settings.fxVolume + 0.1\n"
        "        if settings.fxVolume > 1.0 then\n"
        "            settings.fxVolume = 1.0\n"
        "        end\n"
        "        \n"
        "        if c_update_audio_volume then\n"
        "            c_update_audio_volume()\n"
        "        end\n"
        "    end\n"
        "end\n"
        "\n"
        "function FXVolumeDown()\n"
        "    print(\"[music_functions] FXVolumeDown() called\")\n"
        "    \n"
        "    if settings.fxVolume > 0.0 then\n"
        "        settings.fxVolume = settings.fxVolume - 0.1\n"
        "        if settings.fxVolume < 0.0 then\n"
        "            settings.fxVolume = 0.0\n"
        "        end\n"
        "        \n"
        "        if c_update_audio_volume then\n"
        "            c_update_audio_volume()\n"
        "        end\n"
        "    end\n"
        "end\n"
        "\n"
        "print(\"[music_functions] Music functions script loaded\")\n"
        "return true\n"
    },
    
    /* audio.lua */
    {
        "audio.lua",
        "-- Audio script\n"
        "print(\"[audio] Loading audio script\")\n"
        "\n"
        "-- Define audio settings if they don't exist\n"
        "if not settings then\n"
        "    settings = {}\n"
        "end\n"
        "\n"
        "if settings.playMusic == nil then\n"
        "    settings.playMusic = 1\n"
        "    print(\"[audio] Enabled music in settings\")\n"
        "end\n"
        "\n"
        "if settings.musicVolume == nil then\n"
        "    settings.musicVolume = 0.8\n"
        "    print(\"[audio] Set music volume to 0.8\")\n"
        "end\n"
        "\n"
        "if settings.fxVolume == nil then\n"
        "    settings.fxVolume = 0.8\n"
        "    print(\"[audio] Set FX volume to 0.8\")\n"
        "end\n"
        "\n"
        "-- Update audio volume if function exists\n"
        "if c_update_audio_volume and type(c_update_audio_volume) == \"function\" then\n"
        "    print(\"[audio] Updating audio volume\")\n"
        "    c_update_audio_volume()\n"
        "end\n"
        "\n"
        "print(\"[audio] Audio script loaded\")\n"
        "return true\n"
    },
    
    /* basics.lua */
    {
        "basics.lua",
        "-- Basics script\n"
        "print(\"[basics] Loading basics script\")\n"
        "\n"
        "-- Define app version\n"
        "app_version = 0.71\n"
        "print(\"[basics] App version: \" .. app_version)\n"
        "\n"
        "-- Initialize settings if they don't exist\n"
        "if not settings then\n"
        "    settings = {}\n"
        "    print(\"[basics] Created settings table\")\n"
        "end\n"
        "\n"
        "-- Set default settings\n"
        "if not settings.version then\n"
        "    settings.version = app_version\n"
        "    print(\"[basics] Set settings version to \" .. app_version)\n"
        "end\n"
        "\n"
        "-- Define utility functions\n"
        "function clamp(value, min, max)\n"
        "    if value < min then return min end\n"
        "    if value > max then return max end\n"
        "    return value\n"
        "end\n"
        "\n"
        "print(\"[basics] Basics script loaded\")\n"
        "return true\n"
    },
    
    /* joystick.lua */
    {
        "joystick.lua",
        "-- Joystick script\n"
        "print(\"[joystick] Loading joystick script\")\n"
        "\n"
        "-- Initialize joystick settings\n"
        "if not settings.joystick then\n"
        "    settings.joystick = {}\n"
        "    print(\"[joystick] Created joystick settings table\")\n"
        "end\n"
        "\n"
        "if settings.joystick.enabled == nil then\n"
        "    settings.joystick.enabled = 1\n"
        "    print(\"[joystick] Enabled joystick\")\n"
        "end\n"
        "\n"
        "-- Function to initialize joystick\n"
        "function initJoystick()\n"
        "    print(\"[joystick] Initializing joystick\")\n"
        "    \n"
        "    if c_initJoystick and type(c_initJoystick) == \"function\" then\n"
        "        local result = c_initJoystick()\n"
        "        print(\"[joystick] Joystick initialization result: \" .. tostring(result))\n"
        "        return result\n"
        "    else\n"
        "        print(\"[joystick] c_initJoystick function not available\")\n"
        "        return false\n"
        "    end\n"
        "end\n"
        "\n"
        "-- Initialize joystick if enabled\n"
        "if settings.joystick.enabled == 1 then\n"
        "    print(\"[joystick] Joystick is enabled, initializing\")\n"
        "    initJoystick()\n"
        "else\n"
        "    print(\"[joystick] Joystick is disabled\")\n"
        "end\n"
        "\n"
        "print(\"[joystick] Joystick script loaded\")\n"
        "return true\n"
    },
    
    /* path.lua */
    {
        "path.lua",
        "-- Path script\n"
        "print(\"[path] Loading path script\")\n"
        "\n"
        "-- Function to get a file path\n"
        "function getFilePath(directory, filename)\n"
        "    print(\"[path] Getting file path for \" .. filename .. \" in \" .. directory)\n"
        "    \n"
        "    if c_getFilePath and type(c_getFilePath) == \"function\" then\n"
        "        local path = c_getFilePath(directory, filename)\n"
        "        print(\"[path] File path: \" .. tostring(path))\n"
        "        return path\n"
        "    else\n"
        "        print(\"[path] c_getFilePath function not available\")\n"
        "        return directory .. \"/\" .. filename\n"
        "    end\n"
        "end\n"
        "\n"
        "print(\"[path] Path script loaded\")\n"
        "return true\n"
    },
    
    /* video.lua */
    {
        "video.lua",
        "-- Video script\n"
        "print(\"[video] Loading video script\")\n"
        "\n"
        "-- Initialize video settings\n"
        "if not settings.video then\n"
        "    settings.video = {}\n"
        "    print(\"[video] Created video settings table\")\n"
        "end\n"
        "\n"
        "if settings.video.width == nil then\n"
        "    settings.video.width = 800\n"
        "    print(\"[video] Set default width to 800\")\n"
        "end\n"
        "\n"
        "if settings.video.height == nil then\n"
        "    settings.video.height = 600\n"
        "    print(\"[video] Set default height to 600\")\n"
        "end\n"
        "\n"
        "if settings.video.fullscreen == nil then\n"
        "    settings.video.fullscreen = 0\n"
        "    print(\"[video] Set default fullscreen to 0\")\n"
        "end\n"
        "\n"
        "-- Function to apply video settings\n"
        "function applyVideoSettings()\n"
        "    print(\"[video] Applying video settings\")\n"
        "    \n"
        "    if c_video_restart and type(c_video_restart) == \"function\" then\n"
        "        local result = c_video_restart()\n"
        "        print(\"[video] Video restart result: \" .. tostring(result))\n"
        "        return result\n"
        "    else\n"
        "        print(\"[video] c_video_restart function not available\")\n"
        "        return false\n"
        "    end\n"
        "end\n"
        "\n"
        "print(\"[video] Video script loaded\")\n"
        "return true\n"
    },
    
    /* hud-config.lua */
    {
        "hud-config.lua",
        "-- HUD configuration script\n"
        "print(\"[hud-config] Loading HUD configuration script\")\n"
        "\n"
        "-- Initialize HUD settings\n"
        "if not settings.hud then\n"
        "    settings.hud = {}\n"
        "    print(\"[hud-config] Created HUD settings table\")\n"
        "end\n"
        "\n"
        "if settings.hud.enabled == nil then\n"
        "    settings.hud.enabled = 1\n"
        "    print(\"[hud-config] Enabled HUD\")\n"
        "end\n"
        "\n"
        "if settings.hud.speed == nil then\n"
        "    settings.hud.speed = 1\n"
        "    print(\"[hud-config] Enabled speed display\")\n"
        "end\n"
        "\n"
        "if settings.hud.fps == nil then\n"
        "    settings.hud.fps = 1\n"
        "    print(\"[hud-config] Enabled FPS display\")\n"
        "end\n"
        "\n"
        "print(\"[hud-config] HUD configuration script loaded\")\n"
        "return true\n"
    },
    
    /* hud.lua */
    {
        "hud.lua",
        "-- HUD script\n"
        "print(\"[hud] Loading HUD script\")\n"
        "\n"
        "-- Make sure HUD settings are initialized\n"
        "if not settings.hud then\n"
        "    settings.hud = {}\n"
        "    settings.hud.enabled = 1\n"
        "    settings.hud.speed = 1\n"
        "    settings.hud.fps = 1\n"
        "    print(\"[hud] Initialized HUD settings\")\n"
        "end\n"
        "\n"
        "-- Function to draw HUD\n"
        "function drawHUD()\n"
        "    print(\"[hud] Drawing HUD\")\n"
        "    \n"
        "    if settings.hud.enabled == 0 then\n"
        "        print(\"[hud] HUD is disabled\")\n"
        "        return\n"
        "    end\n"
        "    \n"
        "    -- Draw speed if enabled\n"
        "    if settings.hud.speed == 1 then\n"
        "        print(\"[hud] Drawing speed\")\n"
        "        -- Code to draw speed would go here\n"
        "    end\n"
        "    \n"
        "    -- Draw FPS if enabled\n"
        "    if settings.hud.fps == 1 then\n"
        "        print(\"[hud] Drawing FPS\")\n"
        "        -- Code to draw FPS would go here\n"
        "    end\n"
        "end\n"
        "\n"
        "print(\"[hud] HUD script loaded\")\n"
        "return true\n"
    },
    
    /* gauge.lua */
    {
        "gauge.lua",
        "-- Gauge script\n"
        "print(\"[gauge] Loading gauge script\")\n"
        "\n"
        "-- Function to draw a gauge\n"
        "function drawGauge(x, y, width, height, value, max_value)\n"
        "    print(\"[gauge] Drawing gauge at \" .. x .. \",\" .. y .. \" with value \" .. value .. \"/\" .. max_value)\n"
        "    \n"
        "    -- Calculate fill percentage\n"
        "    local fill = value / max_value\n"
        "    if fill < 0 then fill = 0 end\n"
        "    if fill > 1 then fill = 1 end\n"
        "    \n"
        "    -- Code to draw gauge would go here\n"
        "end\n"
        "\n"
        "print(\"[gauge] Gauge script loaded\")\n"
        "return true\n"
    },
    
    /* config.lua */
    {
        "config.lua",
        "-- Configuration script\n"
        "print(\"[config] Loading configuration script\")\n"
        "\n"
        "-- Initialize settings if they don't exist\n"
        "if not settings then\n"
        "    settings = {}\n"
        "    print(\"[config] Created settings table\")\n"
        "end\n"
        "\n"
        "-- Set default settings\n"
        "if not settings.version then\n"
        "    settings.version = 0.71\n"
        "    print(\"[config] Set settings version to 0.71\")\n"
        "end\n"
        "\n"
        "if not settings.speed then\n"
        "    settings.speed = 10.0\n"
        "    print(\"[config] Set default speed to 10.0\")\n"
        "end\n"
        "\n"
        "if not settings.players then\n"
        "    settings.players = 1\n"
        "    print(\"[config] Set default players to 1\")\n"
        "end\n"
        "\n"
        "if not settings.ai_opponents then\n"
        "    settings.ai_opponents = 3\n"
        "    print(\"[config] Set default AI opponents to 3\")\n"
        "end\n"
        "\n"
        "if not settings.playMusic then\n"
        "    settings.playMusic = 1\n"
        "    print(\"[config] Enabled music\")\n"
        "end\n"
        "\n"
        "if not settings.musicVolume then\n"
        "    settings.musicVolume = 0.8\n"
        "    print(\"[config] Set music volume to 0.8\")\n"
        "end\n"
        "\n"
        "if not settings.fxVolume then\n"
        "    settings.fxVolume = 0.8\n"
        "    print(\"[config] Set FX volume to 0.8\")\n"
        "end\n"
        "\n"
        "-- Mark configuration as complete\n"
        "save_completed = 1\n"
        "\n"
        "print(\"[config] Configuration script loaded\")\n"
        "return true\n"
    },
    
    /* End marker */
    { NULL, NULL }
};

/* Function to get an embedded script by name */
const char* get_embedded_script(const char *name) {
    int i;
    for (i = 0; embedded_scripts[i].name != NULL; i++) {
        if (strcmp(embedded_scripts[i].name, name) == 0) {
            const char* script = embedded_scripts[i].content;
            if (script) {
                // Check for null termination
                size_t len = strlen(script);
                if (script[len] != '\0') {
                    fprintf(stderr, "[error] Embedded script '%s' is not null-terminated!\n", name);
                }
                
                // Print script content and length
                printf("[debug] Embedded script '%s' content:\n%s\n", name, script);
                printf("[debug] Embedded script '%s' length: %zu\n", name, len);
            }
            return script;
        }
    }
    return NULL;
}
