#ifndef SETTINGS_H
#define SETTINGS_H

// Game settings
extern int settings_booster_on;
extern int settings_wall_accel_on;
extern int settings_wall_buster_on;
extern float settings_speed;
extern int settings_ai_level;
extern int settings_erase_crashed;
extern int settings_fast_finish;
extern int settings_camType;
extern int settings_display_type;
extern float settings_map_scale;
extern int settings_players;
extern int settings_ai_opponents;
extern int settings_ai_player1;
extern int settings_ai_player2;
extern int settings_ai_player3;
extern int settings_ai_player4;
extern int settings_mouse_lock_ingame;
extern int settings_mouse_invert_y;
extern int settings_mouse_invert_x;
extern int settings_mipmap_filter;
extern int settings_alpha_trails;
extern int settings_show_glow;
extern int settings_cycle_sharp_edges;
extern float settings_reflection;
extern int settings_show_model;
extern int settings_shadow_volumes_cycle;
extern int settings_arena_outlines;
extern int settings_show_recognizer;
extern int settings_lod;
extern int settings_show_fps;
extern int settings_show_ai_status;
extern int settings_show_scores;
extern int settings_show_speed;
extern int settings_show_console;
extern int settings_show_2d;
extern int settings_fov;
extern int settings_width;
extern int settings_height;
extern int settings_windowMode;
extern int settings_playMusic;
extern int settings_playEffects;
extern float settings_musicVolume;
extern float settings_fxVolume;
extern int settings_loopMusic;
extern char settings_current_level[256];
extern char settings_current_artpack[256];
extern char settings_current_track[256];

#endif // SETTINGS_H